name: Release CI

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  # 'system' or 'module'
  TYPE: system

jobs:
  release:
    name: Create & Publish Release
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
      - name: ğŸ“¡ Checkout
        uses: actions/checkout@v3

      # Configures NodeJS.
      - name: âš™ï¸ Setup NodeJS 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Installs & builds.
      - name: ğŸ”§ Install Dependencies
        run: npm ci
      - name: ğŸ§± Build Project
        run: npm run build

      # Gets the system/module name.
      - name: ğŸ“„ Get Name
        id: name
        uses: notiz-dev/github-action-json-property@release
        with:
          path: ./dist/${{ env.TYPE }}.json
          prop_path: id

      # Gets the version tag.
      - name: ğŸ·ï¸ Get Version Tag
        id: version
        uses: ncipollo/semantic-version-action@v1.0.1

      # Generates the changelog.
      - name: ğŸ“œ Generate Changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3.3.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Creates the ZIP artifact.
      - name: ğŸ“¦ Create ZIP Archive
        run: |
          cd dist/
          zip -r ../${{ steps.name.outputs.prop }}_${{ steps.version.outputs.tag }}.zip *

      # Creates the release with its artifacts and description.
      - name: ğŸš€ Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          allowUpdates: false
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ steps.version.outputs.tag }}
          artifacts: './dist/${{ env.TYPE }}.json, ${{ steps.name.outputs.prop }}_${{ steps.version.outputs.tag }}.zip'
          body: ${{ steps.changelog.outputs.changelog }}
          prerelease: false
          draft: true # TODO change to false when below is enabled


      # Publishes the release to the FoundryVTT's package repository.
      # TODO enable for future release
      # - name: ğŸš© Publish System to FoundryVTT Website
      #   uses: Varriount/fvtt-autopublish@v1.0.9
      #   with:
      #     username: ${{ secrets.FOUNDRY_ADMIN_USERNAME }}
      #     password: ${{ secrets.FOUNDRY_ADMIN_PASSWORD }}
      #     module-id: ${{ secrets.FOUNDRY_ADMIN_MODULE_ID }}
      #     manifest-url: https://github.com/${{ github.repository }}/releases/download/${{ steps.version.outputs.tag }}/${{ env.TYPE }}.json
      #     manifest-file: ./dist/${{ env.TYPE }}.json
